/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/i-bem/__dom/i-bem__dom.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/jquery/jquery.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/loader/_type/loader_type_js.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/jquery/__config/jquery__config.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/desktop.blocks/jquery/__config/jquery__config.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/desktop.blocks/ua/ua.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/objects/objects.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/functions/functions.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/dom/dom.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/i-bem/__dom/_init/i-bem__dom_init.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/i-bem/i-bem.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/i-bem/__internal/i-bem__internal.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/inherit/inherit.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/identify/identify.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/next-tick/next-tick.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/events/events.vanilla.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/i-bem/__dom/_init/i-bem__dom_init_auto.js*/
/*borschik:include:./simple.blocks/test/test.js*/
/*borschik:include:../../../../../../../bem-history-3.2.0/common.blocks/location/location.js*/
/*borschik:include:../../../../../../../bem-history-3.2.0/common.blocks/history/history.js*/
/*borschik:include:../../../../../../../bem-history-3.2.0/common.blocks/uri/uri.js*/
/*borschik:include:../../../../../bower/Users/vitaly/bem/bem-history-3.2.0/bem-core/common.blocks/querystring/__uri/querystring__uri.vanilla.js*/
/*borschik:include:../../../../../../../bem-history-3.2.0/common.blocks/history/_provider/history_provider_history-api.js*/
/*borschik:include:../../../../../../../bem-history-3.2.0/common.blocks/history/_provider/history_provider_hashchange.js*/